config/routes.rb
Rails.application.routes.draw do
 
  get 'recipes/index'
  devise_for :users

  root 'recipes#index'
resources :users
  resources :foods, only: %i[index show new create destroy]
  resources :recipes, only: %i[index edit show new create destroy] do
     resources :recipe_foods, only: %i[new create edit destroy]
  end

  resources :public_recipes, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[index new edit show create destroy]
 end
  
  
  resources :recipes, only: %i[index show new edit create destroy] do
    resources :recipe_foods, only: %i[index new show edit create destroy update edit]
  end

  get '/recipe_foods', to: 'recipe_foods#index'
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user, foreign_key: :user_id
  has_many :recipe_foods, class_name: 'RecipeFoods', foreign_key: :recipe_id, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    puts "Recipe ID: #{params[:id]}"
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class = "form">
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div class='submit-recipe'>
    <%= form.submit "Add recipe" %>
  </div>
  </div>
  
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="recipe">
  <div >
    <h3>
    <strong><%= recipe.name %></strong>
    </h3>
  </div>

  <p>
    <%= truncate(recipe.description, length: 150) %>
  </p>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h2 class="section-title">Recipes</h2>

<div id="newrecipe">
<%= link_to "Add recipe", new_recipe_path %>
</div>

<div id="recipes">
  <% @recipes.includes(:user).each do |recipe| %>
    <div class="recipe-container">
    <%= render recipe %>
    <div class="recipe-options">
    <p>
      <%= link_to "Show recipe", recipe %>
    </p>
    <%= button_to "Delete recipe", recipe, method: :delete %>
    </div>
    </div>
  <% end %>
</div>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>


  <div class="recipe-header">
      
    <div class="button-header">
      <h2 class><%= @recipe.name%></h2>
    </div>

      <div class="publicR">
      <h3 class="r-subtitle">
      Preparation Time: <span class="r-sub-text"><%= @recipe.preparation_time %> min(s)</span>
      </h3>
      
        <% if @recipe.public %>
        <div class="checker-container">
          <input class="check-box" type="checkbox" id="checkbox-check" checked />
          <label class="check-label" for="checkbox-check">Public</label>
        </div>

        <% end %> <% if !@recipe.public %>
        <div class="checker-container">
          <input class="check-box" type="checkbox" id="checkbox-check"/>
          <label class="check-label" for="checkbox-check">Public</label>
        </div>
        <% end %>
      </div>

    <h3 class="r-subtitle">
      Cooking Time: <span class="r-sub-text"><%= @recipe.cooking_time %> min(s)</span>
    </h3>

    <div class="r-sub-text">
      <h3>Step by step description:</h3>
      <p class="r-sub-text"><%= @recipe.description %></p>
    </div>
</div>
  
<div class ="edith-button">
  <button class="back1"><%= link_to "Edit this recipe", edit_recipe_path(@recipe) %></button>
  <br>
  <button class="back1"><%= link_to "Back to recipes", recipes_path %></button>
<br>
  <%= button_to "Destroy this recipe", @recipe, method: :delete %>
</div>

<hr class ="r_show">
<div class= "shopping-button">

<button class="back1">
  <a href="<%= recipe_recipe_foods_path(recipe_id: @recipe) %>" class="btn btn-success">Generate shopping list</a></button><br><br>
  <button class="back1">
  <a href="<%= new_recipe_recipe_food_path(recipe_id: @recipe) %>" class="btn btn-primary">Add ingredient</a>
</button>

</div>

 <div class="column is-three-quarters">
      <%= render partial: "recipe_foods/shared", locals: { recipe_foods: @recipe } %>
  </div>