config/routes.rb
Rails.application.routes.draw do
 
  get 'recipes/index'
  devise_for :users

  root 'recipes#index'
resources :users
  resources :foods, only: %i[index show new create destroy]
  resources :recipes, only: %i[index edit show new create destroy] do
     resources :recipe_foods, only: %i[new create edit destroy]
  end

  resources :public_recipes, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[index new edit show create destroy]
 end
  
  
  resources :recipes, only: %i[index show new edit create destroy] do
    resources :recipe_foods, only: %i[index new show edit create destroy update edit]
  end

  get '/recipe_foods', to: 'recipe_foods#index'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :recipe_foods, class_name: 'RecipeFoods', foreign_key: :food_id, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.save
      redirect_to foods_path,
                  notice: 'Food was added successfully.'
    else
      render :new, alert: 'Failed to add food'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path,
                notice: 'Food was successfully destroyed.'
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div class ="foodshow">
<div class ="foodshow" >
    <h3>
    <%= food.name %></strong>
    </h3>
</div>

</div>

app/views/foods/_form.html.erb
<%= form_with model: @food do |form| %>
<div class="food-form">

  <div class='food-form-cell'>
    <%= form.text_field :name, placeholder: "Name", class:'form-control' %>
  </div>

  <div class='food-form-cell'>
    <%= form.text_field :measurement_unit, placeholder: "Measurement unit", class:'form-control' %>
  </div>

  <div class='food-form-cell'>
    <%= form.text_field :price, placeholder: "Unit price", class:'form-control' %>
  </div>

  <div class='submit-btn'>
    <%= form.submit "Add food" %>
  </div>
</div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="addFoods">

<h1>Food List</h1>

<button>
  <%= link_to "Add food", new_food_path, data: { turbo_frame: 'modal' } %>
</button>

<table class='foods-table'>
    <thead>
        <tr>
          <th>Food</th>
          <th>Measurement unit</th>
          <th>Unit price</th>
          <th>Actions</th>
        </tr>
    </thead>

    <tbody>
      <% @foods.includes(:recipe_foods).each do |f| %>
        <tr>
            <td><%= f.name %></td>
            <td><%= f.measurement_unit %></td>
            <td><%= f.price %></td>
            <td><%= link_to "Delete", food_path(f.id), data: {
                         turbo_method: :delete,
                         turbo_confirm: "Are you sure you want to delete this food item?"
                      }, class: "delete-food-cell" %></td>
        </tr>
       <% end %>
    </tbody>
</table>
</div>

app/views/foods/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= render "form", post: @food %>
<% end %>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>