config/routes.rb
Rails.application.routes.draw do
 
  get 'recipes/index'
  devise_for :users

  root 'recipes#index'
resources :users
  resources :foods, only: %i[index show new create destroy]
  resources :recipes, only: %i[index edit show new create destroy] do
     resources :recipe_foods, only: %i[new create edit destroy]
  end

  resources :public_recipes, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: %i[index show new create edit update destroy] do
    resources :recipe_foods, only: %i[index new edit show create destroy]
 end
  
  
  resources :recipes, only: %i[index show new edit create destroy] do
    resources :recipe_foods, only: %i[index new show edit create destroy update edit]
  end

  get '/recipe_foods', to: 'recipe_foods#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
      <div>
        <h1>Recipes</h1>
      </div>
      <ul id="linkList">
      <li><%= link_to 'Users' , users_path %></li>
        <li><%= link_to 'Recipes' , root_path %></li>
        <li><%= link_to 'Foods' , foods_path %></li>
        <li><%= link_to 'Public Recipes' , public_recipes_path %></li>
      </ul>
      <ul id="account-edith">
        <% if user_signed_in? %>
        <h3><%= "Hello! #{current_user.name}" %></h3>
        <li><%= link_to 'Sign out' ,destroy_user_session_path, method: :delete %></li>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </header>
    <div id="pageBody">
    <%= yield %>
    </div>
</html>